---
version: '2.1'
networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.0/24
services:
  app:
    build:
      context: '.'
      dockerfile: "docker/app/Dockerfile"
      args:
        - ARG_JAR_FILE=/target/scheduler-application-server-0.0.1-SNAPSHOT.jar
    container_name: app.scheduler.local
    hostname: app
    networks:
      - custom_network
    ports:
      - 8080:8080
    environment:
      - APP_CONTEXT=local
    #volumes:
      #- './target:/app:rw'
      #- '../../src/main/resources:/app/confs:rw'

